spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mybatis-example
  # session 失效时间
  session:
    timeout: 86400

  address: 0.0.0.0
