spring:
  application:
    name:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mybatis-example
server:
  port: 8080
  servlet:
    context-path: /api


